export default {
  onBoardOne: require('../../Assets/Image/onBoardOne.png'),
  onBoardTwo: require('../../Assets/Image/onBoardTwo.png'),
  onBoardThree: require('../../Assets/Image/onBoardThree.png'),
  BackRound: require('../../Assets/Image/backRound.png'),
  // beginner: require('../../Assets/Image/Beginner.png'),
  // intermediate: require('../../Assets/Image/Intermediate.png'),
  // advances: require('../../Assets/Image/Advanced.png'),
  arm: require('../../Assets/Image/Arm.png'),
  abs: require('../../Assets/Image/Abs.png'),
  butt: require('../../Assets/Image/Butt.png'),
  leg: require('../../Assets/Image/Leg.png'),
  homeBack: require('../../Assets/Image/HomeBackImg.png'),
  trainingOne: require('../../Assets/Image/TrainingOne.png'),
  trainingTwo: require('../../Assets/Image/TrainingTwo.png'),
  trainingThree: require('../../Assets/Image/TrainingThree.png'),
  challengesOne: require('../../Assets/Image/ChallengesOne.png'),
  challengesTwo: require('../../Assets/Image/ChallengesTwo.png'),
  challengesThree: require('../../Assets/Image/ChallengesThree.png'),
  challengesFour: require('../../Assets/Image/challengesFour.png'),
  challengesFive: require('../../Assets/Image/challengesFive.png'),
  challengesSix: require('../../Assets/Image/challengesSix.png'),
  challengesSeven: require('../../Assets/Image/challengesSeven.png'),
  challengesEight: require('../../Assets/Image/challengesEight.png'),
  challengesNine: require('../../Assets/Image/challengesNine.png'),

  FitnessBanner: require('../../Assets/Image/FitnessBanner.png'),
  Str: require('../../Assets/Image/FitnessBanner.png'),

  StretchOne: require('../../Assets/Image/StretchOne.png'),
  StretchTwo: require('../../Assets/Image/StretchTwo.png'),
  StretchThree: require('../../Assets/Image/StretchThree.png'),
  StretchFour: require('../../Assets/Image/StretchFour.png'),
  StretchFive: require('../../Assets/Image/StretchFive.png'),
  StretchSix: require('../../Assets/Image/StretchSix.png'),
  StretchSeven: require('../../Assets/Image/StretchSeven.png'),
  StretchEight: require('../../Assets/Image/StretchEight.png'),
  StretchNine: require('../../Assets/Image/StretchNine.png'),
  StretchTen: require('../../Assets/Image/StretchTen.png'),
  StretchEleven: require('../../Assets/Image/StretchEleven.png'),
  StretchTwelve: require('../../Assets/Image/StretchTwelve.png'),

  WarmUpVideo: require('../../Assets/Image/WarmUpVideo.png'),

  ChallengesWorkOut: require('../../Assets/Image/ChallangesWorkout.png'),
  SkipWorkout: require('../../Assets/Image/SkipWorkOut.png'),
  Profile: require('../../Assets/Image/Profile.png'),
  CouchProfile: require('../../Assets/Image/CouchProfile.png'),
  CheckMsg: require('../../Assets/Image/CheckMsg.png'),
  Map: require('../../Assets/Image/Map.png'),

  PlanOne: require('../../Assets/Image/PlanOne.png'),
  PlanTwo: require('../../Assets/Image/PlanTwo.png'),
  PlanThree: require('../../Assets/Image/PlanThree.png'),
  PlanFour: require('../../Assets/Image/PlanFour.png'),
  PlanCouch1: require('../../Assets/Image/PlanCouch1.png'),
  PlanCouch2: require('../../Assets/Image/PlanCouch2.png'),
  PlanCouch3: require('../../Assets/Image/PlanCouch3.png'),
  PlanCouch4: require('../../Assets/Image/PlanCouch4.png'),
  PlanCouch5: require('../../Assets/Image/PlanCouch5.png'),
  PlanCouch6: require('../../Assets/Image/PlanCouch6.png'),
  PlanCouch7: require('../../Assets/Image/PlanCouch7.png'),
  more: require('../../Assets/Image/More.png'),

  ChatList1: require('../../Assets/Image/ChatList1.png'),
  ChatList2: require('../../Assets/Image/ChatList2.png'),
  ChatList3: require('../../Assets/Image/ChatList3.png'),
  ChatList4: require('../../Assets/Image/ChatList4.png'),


};
